version: 2
updates:
  - package-ecosystem: gomod
    directory: /worker
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: /server/frontend
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
