version: "3"

services:
  jinya-backup-db:
    container_name: jinya-backup-db
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jinya
      POSTGRES_PASSWORD: jinya
    restart: always
  jinya-alpine:
    image: quay.imanuel.dev/dockerhub/library---golang:1.20-alpine
    volumes:
      - .:/tmp/go