name: jinya_backup
description: The server component for Jinya Backup
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  postgres: ^2.4.3
  crypto: ^3.0.1
  dotenv: ^3.0.0
  shelf_router: ^1.1.2
  uuid: ^3.0.6
  cryptography: ^2.0.5
  ftpconnect: ^1.0.1
  pedantic: ^1.11.1
  path: ^1.8.1
  mime_type: ^1.0.0
  ninja: ^3.0.7
